spring:
  application:
    name: crm

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

config:
  keycloak:
    server-url: "http://localhost:9090/"
    realm: "crm"
    admin-cli: "admin-cli"
    admin-user: "admin_1"
    password: "1234"

server:
  port: 8082
