spring:
  application:
    name: crm

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

gmail:
  client-id:
  client-secret:
  refresh-token:

gmail-account:
  application_name: "WA2 FINAL PROJECT"

camel:
  component:
    google-mail:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

server:
  port: 8083